apiVersion: v1
kind: Deployment
metadata:
  name: selenium-rep
  namespace: selenium-ingress
spec:
  replicas: 3
  selector:
    app: selenium-chrome
  template:
    metadata:
      name: selenium-chrome
      namespace: selenium-ingress
      labels:
        app: selenium-chrome
    spec:
      containers:
        - name: node-chrome
          image: selenium/node-chrome:104.0
          ports:
            - name: http
              containerPort: 5555
          env:
            - name: HUB_HOST 
              value: "selenium-hub"
            - name: HUB_PORT
              value: "80"
            - name: HUB_PORT_4444_TCP_ADDR 
              value: "selenium-hub"
            - name: HUB_PORT_4444_TCP_PORT 
              value: "4444"
