apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome
  template:
    metadata:
      name: selenium-chrome
      namespace: ingress-nginx
      labels:
        app: selenium-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:104.0
          ports:
            - containerPort: 5555
          env:
           - name: HUB_PORT_4444_TCP_ADDR
             value: "selenium-hub"
           - name: HUB_PORT_4444_TCP_PORT
             value: "4444"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
